---
abstract: 'Information about Perl modules'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Info
provides:
  B::BUtils:
    file: lib/B/BUtils.pm
    version: 0
  B::Module::Info:
    file: lib/B/Module/Info.pm
    version: 0.24
  B::Utils:
    file: lib/B/BUtils.pm
    version: 0.04_02
  Module::Info:
    file: lib/Module/Info.pm
    version: 0.34
  Module::Info::Safe:
    file: lib/Module/Info.pm
    version: 0
  Module::Info::Unsafe:
    file: lib/Module/Info.pm
    version: 0
requires:
  File::Spec: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.34
