# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Info
version:      0.23
version_from: lib/Module/Info.pm
installdirs:  site
requires:
    File::Spec:                    0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
