--- #YAML:1.0
name: Module-Info
version: 0.28
author:
  - Mattia Barbon <mbarbon@cpan.org>
abstract: Information about Perl modules
license: perl
requires:
  File::Spec: 0.08
dynamic_config: 0
provides:
  B::Module::Info:
    file: lib/B/Module/Info.pm
    version: 0.24
  B::Utils:
    file: lib/B/Utils.pm
    version: 0.04_01
  Module::Info:
    file: lib/Module/Info.pm
    version: 0.28
  Module::Info::Safe:
    file: lib/Module/Info.pm
    version: 0.28
  Module::Info::Unsafe:
    file: lib/Module/Info.pm
    version: 0.28
  Module::Info::_version:
    file: lib/Module/Info.pm
    version: 0.28
generated_by: Module::Build version 0.2607
