---
abstract: 'Information about Perl modules'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Info
no_index:
  directory:
    - t
    - inc
requires:
  B: '0'
  B::Utils: '0.27'
  Carp: '0'
  File::Spec: '0.8'
  perl: '5.006'
  strict: '0'
version: 0.35_06
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
