# http://module-build.sourceforge.net/META-spec.html
name:         Module-Info
version:      0.31
version_from: lib/Module/Info.pm
installdirs:  site
author:       Mattia Barbon <mbarbon@cpan.org>
abstract: Information about Perl modules
license: perl
requires:
  File::Spec: 0.8
#build_requires:
no_index:
  directory:
    - t

# extras.
dynamic_config: 0

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.07, EUMM-6.32.
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
