# http://module-build.sourceforge.net/META-spec.html
name:         Module-Info
version:      0.33
version_from: lib/Module/Info.pm
installdirs:  site
author:       ARRAY(0x1009adfe8)
abstract:     Information about Perl modules
license:      perl
requires:
  File::Spec: 0.8
#build_requires:
no_index:
  directory:
    - t

# extras.
dynamic_config: 0

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.62.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
